// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.example.demo.rpc;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.rpc.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
